spring.application.name=banco-legacy-account-service
spring.config.import=configserver:http://localhost:8888
spring.datasource.password=${DB_PASSWORD}
security.jwt.public-key=${JWT_PUBLIC_KEY}
server.ssl.key-store=${ACCOUNT_TLS_KEYSTORE}
server.ssl.key-store-password=${ACCOUNT_TLS_KEYSTORE_PASSWORD}
