spring.application.name=banco-legacy-account-service
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.datasource.password=${DB_PASSWORD}
security.jwt.public-key=${JWT_PUBLIC_KEY}
server.ssl.key-store=${ACCOUNT_TLS_KEYSTORE}
server.ssl.key-store-password=${ACCOUNT_TLS_KEYSTORE_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false
banking.kafka.financial-topic=banco.operaciones.completadas.v1

spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.delivery.timeout.ms=10000
