package com.duoc.banco_legacy.core.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(LegacyAccountReadRepository.class)
class LegacyAccountReadRepositoryTests {
    @Autowired LegacyAccountReadRepository repository;
    @Autowired JdbcClient jdbcClient;

    @BeforeEach
    void prepareSchema() {
        jdbcClient.sql("CREATE TABLE IF NOT EXISTS interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY, cuenta_id BIGINT, nombre VARCHAR(120), saldo_original DECIMAL(19,2), tasa DECIMAL(8,4), saldo_procesado DECIMAL(19,2), tipo VARCHAR(20))").update();
        jdbcClient.sql("CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))").update();
        jdbcClient.sql("CREATE TABLE IF NOT EXISTS transaccion_procesada (id BIGINT GENERATED BY DEFAULT AS IDENTITY, transaccion_id BIGINT, fecha DATE, monto DECIMAL(19,2), tipo VARCHAR(20), anomalia BOOLEAN)").update();
        jdbcClient.sql("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.01,1010,'ahorro')").update();
        jdbcClient.sql("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-01-01','deposito',100,'Abono')").update();
    }

    @Test
    void consultaSaldoYMovimientosProcesados() {
        assertThat(repository.findLatestBalance(101)).get().extracting("holderName").isEqualTo("Ana");
        assertThat(repository.findRecentMovements(101, 3)).hasSize(1)
                .first().extracting("description").isEqualTo("Abono");
    }


    @Test
    void limitsAndDeterministicOrderAcrossProjections() {
        for (int i = 1; i <= 25; i++) {
            jdbcClient.sql("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-02-01','deposito',:amount,'Detalle')")
                    .param("amount", i).update();
        }
        assertThat(repository.findRecentMovements(101, 20)).hasSize(20)
                .extracting(m -> m.amount().intValue()).containsExactly(
                        25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6);
        assertThat(repository.findCompactMovements(101, 5)).hasSize(5)
                .extracting(m -> m.amount().intValue()).containsExactly(25,24,23,22,21);
        assertThat(repository.findEssentialMovements(101, 3)).hasSize(3)
                .extracting(m -> m.amount().intValue()).containsExactly(25,24,23);
    }

    @Test
    void optimizedBalancesSelectLatestAndPreserveMissingAccount() {
        jdbcClient.sql("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.02,1020,'ahorro')").update();
        assertThat(repository.findLatestBalance(101).orElseThrow().processedBalance()).isEqualByComparingTo("1020");
        assertThat(repository.findSummary(101).orElseThrow().balance()).isEqualByComparingTo("1020");
        assertThat(repository.findAvailableBalance(101).orElseThrow()).isEqualByComparingTo("1020");
        assertThat(repository.accountExists(101)).isTrue();
        assertThat(repository.accountExists(999)).isFalse();
        assertThat(repository.findSummary(999)).isEmpty();
        assertThat(repository.findAvailableBalance(999)).isEmpty();
    }

    @Test
    void anomaliesAreGlobalOrderedAndLimited() {
        for (int i=1; i<=12; i++) {
            jdbcClient.sql("INSERT INTO transaccion_procesada (transaccion_id,fecha,monto,tipo,anomalia) VALUES (:id,DATE '2026-02-01',2500,'debito',TRUE)")
                    .param("id",i).update();
        }
        assertThat(repository.findRecentAnomalies(10)).hasSize(10)
                .extracting(m -> m.transactionId()).containsExactly(12L,11L,10L,9L,8L,7L,6L,5L,4L,3L);
    }

    @Test
    void rejectsUnboundedLimits() {
        org.assertj.core.api.Assertions.assertThatThrownBy(() -> repository.findRecentMovements(101,0))
                .isInstanceOf(IllegalArgumentException.class);
        org.assertj.core.api.Assertions.assertThatThrownBy(() -> repository.findCompactMovements(101,101))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @SpringBootConfiguration
    @EnableAutoConfiguration
    static class TestApplication {
    }
}
