package com.duoc.banco_legacy.core.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(LegacyAccountReadRepository.class)
class LegacyAccountReadRepositoryTests {
    @Autowired LegacyAccountReadRepository repository;
    @Autowired JdbcClient jdbcClient;

    @BeforeEach
    void prepareSchema() {
        jdbcClient.sql("CREATE TABLE interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY, cuenta_id BIGINT, nombre VARCHAR(120), saldo_original DECIMAL(19,2), tasa DECIMAL(8,4), saldo_procesado DECIMAL(19,2), tipo VARCHAR(20))").update();
        jdbcClient.sql("CREATE TABLE movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))").update();
        jdbcClient.sql("CREATE TABLE transaccion_procesada (id BIGINT GENERATED BY DEFAULT AS IDENTITY, transaccion_id BIGINT, fecha DATE, monto DECIMAL(19,2), tipo VARCHAR(20), anomalia BOOLEAN)").update();
        jdbcClient.sql("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.01,1010,'ahorro')").update();
        jdbcClient.sql("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-01-01','deposito',100,'Abono')").update();
    }

    @Test
    void consultaSaldoYMovimientosProcesados() {
        assertThat(repository.findLatestBalance(101)).get().extracting("holderName").isEqualTo("Ana");
        assertThat(repository.findRecentMovements(101, 3)).hasSize(1)
                .first().extracting("description").isEqualTo("Abono");
    }

    @SpringBootConfiguration
    @EnableAutoConfiguration
    static class TestApplication {
    }
}
