package com.duoc.banco_legacy.core.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.math.BigDecimal;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.IncorrectUpdateSemanticsDataAccessException;
import org.springframework.jdbc.core.simple.JdbcClient;

@JdbcTest
@Import(LegacyAccountWithdrawalRepository.class)
class LegacyAccountWithdrawalRepositoryTests {
    @Autowired LegacyAccountWithdrawalRepository repository;
    @Autowired JdbcClient jdbcClient;

    @BeforeEach
    void prepareSchema() {
        jdbcClient.sql("CREATE TABLE IF NOT EXISTS interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, saldo_procesado DECIMAL(19,2))").update();
        jdbcClient.sql("CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))").update();
        jdbcClient.sql("DELETE FROM movimiento_anual_procesado").update();
        jdbcClient.sql("DELETE FROM interes_procesado").update();
        jdbcClient.sql("INSERT INTO interes_procesado (cuenta_id,saldo_procesado) VALUES (101,100),(101,150)").update();
    }

    @Test
    void locksLatestRowAndUpdatesThatExactRow() {
        var locked = repository.lockLatestBalance(101).orElseThrow();

        assertThat(locked.balance()).isEqualByComparingTo("150");
        repository.updateBalance(locked.rowId(), new BigDecimal("50"));

        assertThat(jdbcClient.sql("SELECT saldo_procesado FROM interes_procesado WHERE id=:id")
                .param("id", locked.rowId()).query(BigDecimal.class).single()).isEqualByComparingTo("50");
        assertThat(jdbcClient.sql("SELECT saldo_procesado FROM interes_procesado WHERE cuenta_id=101 ORDER BY id LIMIT 1")
                .query(BigDecimal.class).single()).isEqualByComparingTo("100");
    }

    @Test
    void rejectsUpdateWhenItDoesNotAffectExactlyOneRow() {
        assertThatThrownBy(() -> repository.updateBalance(Long.MAX_VALUE, BigDecimal.ONE))
                .isInstanceOf(IncorrectUpdateSemanticsDataAccessException.class)
                .hasMessageContaining("filas afectadas: 0");
    }

    @Test
    void insertsExactlyOneWithdrawalMovement() {
        repository.insertWithdrawalMovement(101, new BigDecimal("25.50"));

        assertThat(jdbcClient.sql("SELECT COUNT(*) FROM movimiento_anual_procesado WHERE cuenta_id=101 AND tipo_transaccion='retiro' AND monto=25.50 AND descripcion='Retiro ATM'")
                .query(Long.class).single()).isEqualTo(1L);
    }
}
