spring.application.name=banco-legacy-mobile-bff
spring.config.import=configserver:http://localhost:8888
security.jwt.public-key=${JWT_PUBLIC_KEY}
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD:changeit}
