spring.application.name=banco-legacy-batch
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banco_legacy_batch}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.sql.init.mode=always

batch.input-directory=${BATCH_INPUT_DIR:C:/Dev/Duoc/DBE3/bank_legacy_data/data/semana_3}
batch.run-on-startup=${BATCH_RUN_ON_STARTUP:true}
batch.partition.grid-size=${BATCH_GRID_SIZE:4}
batch.partition.thread-count=${BATCH_THREAD_COUNT:4}
batch.chunk-size=${BATCH_CHUNK_SIZE:100}
batch.skip-limit=${BATCH_SKIP_LIMIT:1000}
