CREATE TABLE IF NOT EXISTS transaccion_procesada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    monto DECIMAL(19, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    anomalia BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS anomaly_event_outbox (
    event_id UUID PRIMARY KEY,
    correlation_id VARCHAR(120) NOT NULL,
    event_version INTEGER NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    anomaly_reason VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    publish_attempts INTEGER NOT NULL DEFAULT 0,
    published_at TIMESTAMP WITH TIME ZONE NULL,
    last_error VARCHAR(500) NULL,
    CONSTRAINT chk_anomaly_outbox_version CHECK (event_version > 0),
    CONSTRAINT chk_anomaly_outbox_amount CHECK (amount > 0),
    CONSTRAINT chk_anomaly_outbox_status CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT chk_anomaly_outbox_attempts CHECK (publish_attempts >= 0),
    CONSTRAINT chk_anomaly_outbox_published CHECK (
        (status = 'PUBLISHED' AND published_at IS NOT NULL)
        OR (status <> 'PUBLISHED' AND published_at IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS interes_procesado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    saldo_original DECIMAL(19, 2) NOT NULL,
    tasa DECIMAL(8, 4) NOT NULL,
    saldo_procesado DECIMAL(19, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    tipo_transaccion VARCHAR(30) NOT NULL,
    monto DECIMAL(19, 2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
);
