CREATE TABLE IF NOT EXISTS transaccion_procesada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    monto DECIMAL(19, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    anomalia BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS interes_procesado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    saldo_original DECIMAL(19, 2) NOT NULL,
    tasa DECIMAL(8, 4) NOT NULL,
    saldo_procesado DECIMAL(19, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    tipo_transaccion VARCHAR(30) NOT NULL,
    monto DECIMAL(19, 2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
);
