package com.duoc.banco_legacy.account;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest
@AutoConfigureMockMvc
class AccountServiceIntegrationTests extends JwtTestSupport {
    @Autowired MockMvc mvc;
    @Autowired JdbcTemplate jdbc;

    @BeforeEach
    void seedIsolatedH2() throws Exception {
        try (var connection = jdbc.getDataSource().getConnection()) {
            if (!connection.getMetaData().getURL().startsWith("jdbc:h2:mem:")) {
                throw new IllegalStateException("Tests require isolated H2");
            }
        }
        jdbc.execute("CREATE TABLE IF NOT EXISTS interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, nombre VARCHAR(120), saldo_original DECIMAL(19,2), tasa DECIMAL(8,4), saldo_procesado DECIMAL(19,2), tipo VARCHAR(20))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS transaccion_procesada (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaccion_id BIGINT, fecha DATE, monto DECIMAL(19,2), tipo VARCHAR(20), anomalia BOOLEAN)");
        jdbc.update("DELETE FROM movimiento_anual_procesado");
        jdbc.update("DELETE FROM interes_procesado");
        jdbc.update("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.01,1010,'ahorro')");
        jdbc.update("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-01-01','deposito',100,'Detalle')");
    }

    @Test
    void mobileTokenReadsSummaryAndMovements() throws Exception {
        mvc.perform(get("/internal/accounts/101/summary").with(bearer("MOBILE")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.balance").value(1010));
        mvc.perform(get("/internal/accounts/101/movements").with(bearer("MOBILE")))
                .andExpect(status().isOk()).andExpect(jsonPath("$[0].amount").value(100));
    }

    @Test
    void internalEndpointsEnforceChannelRoles() throws Exception {
        String[] paths = {"/internal/accounts/101/web-dashboard", "/internal/accounts/101/summary",
                "/internal/accounts/101/atm-balance"};
        String[] roles = {"WEB", "MOBILE", "ATM"};
        for (int path = 0; path < paths.length; path++) {
            for (int role = 0; role < roles.length; role++) {
                mvc.perform(get(paths[path]).with(bearer(roles[role])))
                        .andExpect(path == role ? status().isOk() : status().isForbidden());
            }
        }
        mvc.perform(get("/internal/accounts/101/atm-movements").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$[0].type").value("deposito"));
        mvc.perform(get("/internal/accounts/101/web-dashboard").with(bearer("WEB")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.holderName").value("Ana"))
                .andExpect(jsonPath("$.movements[0].description").value("Detalle"));
    }

    @Test
    void rejectsAlteredAndExpiredTokens() throws Exception {
        var signedRequest = new org.springframework.mock.web.MockHttpServletRequest();
        bearer("MOBILE").postProcessRequest(signedRequest);
        String[] parts = signedRequest.getHeader("Authorization").substring(7).split("\\.");
        String payload = new String(java.util.Base64.getUrlDecoder().decode(parts[1]),
                java.nio.charset.StandardCharsets.UTF_8);
        parts[1] = java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(
                payload.replace("test-user", "attacker").getBytes(java.nio.charset.StandardCharsets.UTF_8));
        mvc.perform(get("/internal/accounts/101/summary")
                .header("Authorization", "Bearer " + String.join(".", parts)))
                .andExpect(status().isUnauthorized());
        mvc.perform(get("/internal/accounts/101/summary")
                .with(bearerExpired("MOBILE"))).andExpect(status().isUnauthorized());
    }

    @Test
    void directCallWithoutTokenIsUnauthorized() throws Exception {
        mvc.perform(get("/internal/accounts/101/summary")).andExpect(status().isUnauthorized());
    }

    @Test
    void missingAccountIsNotFound() throws Exception {
        mvc.perform(get("/internal/accounts/999/summary").with(bearer("MOBILE")))
                .andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("ACCOUNT_NOT_FOUND"));
    }

    @Test
    void atmReadReflectsCommittedBalanceAndMovement() throws Exception {
        jdbc.update("UPDATE interes_procesado SET saldo_procesado=910 WHERE cuenta_id=101");
        jdbc.update("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) "
                + "VALUES (101,DATE '2026-01-02','retiro',100,'Retiro ATM')");
        mvc.perform(get("/internal/accounts/101/atm-balance").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.availableBalance").value(910));
        mvc.perform(get("/internal/accounts/101/atm-movements").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$[0].type").value("retiro"))
                .andExpect(jsonPath("$[0].amount").value(100));
    }
}
