spring.application.name=banco-legacy-atm-bff
spring.config.import=configserver:http://localhost:8888
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
security.jwt.public-key=${JWT_PUBLIC_KEY}
# TLS directo; PKCS12 local generado con el procedimiento del profesor.
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD:changeit}
