spring.application.name=banco-legacy-web-bff
spring.config.import=configserver:http://localhost:8888
security.jwt.public-key=${JWT_PUBLIC_KEY}
# TLS directo; PKCS12 local generado con el procedimiento del profesor.
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD:changeit}
