spring.application.name=banco-legacy-customer-service
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
security.jwt.public-key=${JWT_PUBLIC_KEY}
server.ssl.key-store=${SERVER_SSL_KEY_STORE}
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD}