package com.duoc.banco_legacy.atm;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.mock.mockito.SpyBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import com.duoc.banco_legacy.core.repository.LegacyAccountReadRepository;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:atm_integration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver","spring.datasource.username=sa","spring.datasource.password=",
        "spring.sql.init.mode=never"})
@AutoConfigureMockMvc
class AtmDataIntegrationTests extends JwtTestSupport {
    @Autowired MockMvc mvc;
    @Autowired JdbcTemplate jdbc;
    @SpyBean LegacyAccountReadRepository repository;
    @BeforeEach void seedIsolatedH2() throws Exception {
        try(var connection = jdbc.getDataSource().getConnection()) {
            if (!connection.getMetaData().getURL().startsWith("jdbc:h2:mem:")) throw new IllegalStateException("Tests require isolated H2");
        }
        jdbc.execute("CREATE TABLE IF NOT EXISTS interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, nombre VARCHAR(120), saldo_original DECIMAL(19,2), tasa DECIMAL(8,4), saldo_procesado DECIMAL(19,2), tipo VARCHAR(20))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS transaccion_procesada (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaccion_id BIGINT, fecha DATE, monto DECIMAL(19,2), tipo VARCHAR(20), anomalia BOOLEAN)");
        jdbc.update("DELETE FROM interes_procesado");
        jdbc.update("DELETE FROM movimiento_anual_procesado");
        jdbc.update("DELETE FROM transaccion_procesada");
        jdbc.update("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.01,1010,'ahorro'),(102,'Beto',100,0.01,101,'ahorro')");
        for(int i=1;i<=25;i++) jdbc.update("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-01-01','deposito',?,'Detalle')",i);
        for(int i=1;i<=12;i++) jdbc.update("INSERT INTO transaccion_procesada (transaccion_id,fecha,monto,tipo,anomalia) VALUES (?,DATE '2026-01-01',2500,'debito',TRUE)",i);
    }
    @Test void fullReadPathWithRealJwtAndJdbc() throws Exception {
        mvc.perform(get("/api/atm/accounts/101/balance").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.availableBalance").value(1010));
    }
    @Test void missingAccountIs404() throws Exception {
        mvc.perform(get("/api/atm/accounts/999/balance").with(bearer("ATM"))).andExpect(status().isNotFound());
    }

    @Test void movementsAreOrderedAndLimited() throws Exception {
        mvc.perform(get("/api/atm/accounts/101/movements").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(3))
                .andExpect(jsonPath("$[0].amount").value(25))
                .andExpect(jsonPath("$[0].description").doesNotExist()).andExpect(jsonPath("$[0].date").doesNotExist());
    }
    @Test void missingAccountMovementsReturn404() throws Exception {
        mvc.perform(get("/api/atm/accounts/999/movements").with(bearer("ATM"))).andExpect(status().isNotFound());
    }
    @Test void existingAccountWithoutMovementsReturnsEmptyArray() throws Exception {
        mvc.perform(get("/api/atm/accounts/102/movements").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(0));
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(strings={"{\"amount\":0}","{\"amount\":-1}","{\"amount\":null}","{}","{\"amount\":0.001}","{\"amount\":100000000000000000}"})
    void invalidWithdrawalIs400(String body) throws Exception {
        mvc.perform(post("/api/atm/accounts/101/withdrawals").with(bearer("ATM"))
                .contentType("application/json").content(body)).andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("WITHDRAWAL_REJECTED"));
    }
    @Test void withdrawalsDoNotChangeDatabase() throws Exception {
        var before = jdbc.queryForList("SELECT * FROM interes_procesado ORDER BY id");
        for (int i=0; i<2; i++) {
            mvc.perform(post("/api/atm/accounts/101/withdrawals").with(bearer("ATM"))
                    .contentType("application/json").content("{\"amount\":100}"))
                    .andExpect(status().isOk()).andExpect(jsonPath("$.status").value("SIMULATED"))
                    .andExpect(jsonPath("$.projectedBalance").value(910));
        }
        org.assertj.core.api.Assertions.assertThat(jdbc.queryForList("SELECT * FROM interes_procesado ORDER BY id")).isEqualTo(before);
    }
    @Test void missingWithdrawalAccountIs404() throws Exception {
        mvc.perform(post("/api/atm/accounts/999/withdrawals").with(bearer("ATM"))
                .contentType("application/json").content("{\"amount\":1}")).andExpect(status().isNotFound());
    }

}
