package com.duoc.banco_legacy.atm;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.mock.mockito.SpyBean;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import com.duoc.banco_legacy.core.repository.LegacyAccountReadRepository;
import com.duoc.banco_legacy.atm.service.AtmWithdrawalService;
import com.duoc.banco_legacy.atm.client.AccountServiceClient;
import com.duoc.banco_legacy.atm.dto.AtmBalance;
import com.duoc.banco_legacy.atm.dto.AtmMovement;
import com.duoc.banco_legacy.atm.service.WithdrawalRejectedException;
import java.math.BigDecimal;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:atm_integration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver","spring.datasource.username=sa","spring.datasource.password=",
        "spring.sql.init.mode=never"})
@AutoConfigureMockMvc
class AtmDataIntegrationTests extends JwtTestSupport {
    @Autowired MockMvc mvc;
    @Autowired JdbcTemplate jdbc;
    @Autowired AtmWithdrawalService withdrawalService;
    @SpyBean LegacyAccountReadRepository repository;
    @MockBean AccountServiceClient remoteClient;
    @BeforeEach void seedIsolatedH2() throws Exception {
        try(var connection = jdbc.getDataSource().getConnection()) {
            if (!connection.getMetaData().getURL().startsWith("jdbc:h2:mem:")) throw new IllegalStateException("Tests require isolated H2");
        }
        jdbc.execute("CREATE TABLE IF NOT EXISTS interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, nombre VARCHAR(120), saldo_original DECIMAL(19,2), tasa DECIMAL(8,4), saldo_procesado DECIMAL(19,2), tipo VARCHAR(20))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS transaccion_procesada (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaccion_id BIGINT, fecha DATE, monto DECIMAL(19,2), tipo VARCHAR(20), anomalia BOOLEAN)");
        jdbc.execute("ALTER TABLE movimiento_anual_procesado DROP CONSTRAINT IF EXISTS reject_atm_withdrawal");
        jdbc.update("DELETE FROM interes_procesado");
        jdbc.update("DELETE FROM movimiento_anual_procesado");
        jdbc.update("DELETE FROM transaccion_procesada");
        jdbc.update("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.01,1010,'ahorro'),(102,'Beto',100,0.01,101,'ahorro')");
        for(int i=1;i<=25;i++) jdbc.update("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-01-01','deposito',?,'Detalle')",i);
        for(int i=1;i<=12;i++) jdbc.update("INSERT INTO transaccion_procesada (transaccion_id,fecha,monto,tipo,anomalia) VALUES (?,DATE '2026-01-01',2500,'debito',TRUE)",i);
        when(remoteClient.getBalance(eq(101L), anyString())).thenReturn(new AtmBalance(101, new BigDecimal("1010")));
        when(remoteClient.getBalance(eq(999L), anyString())).thenThrow(new com.duoc.banco_legacy.core.exception.AccountNotFoundException(999));
        when(remoteClient.getMovements(eq(101L), anyString())).thenReturn(List.of(
                new AtmMovement("deposito", new BigDecimal("25")),
                new AtmMovement("deposito", new BigDecimal("24")),
                new AtmMovement("deposito", new BigDecimal("23"))));
        when(remoteClient.getMovements(eq(999L), anyString())).thenThrow(new com.duoc.banco_legacy.core.exception.AccountNotFoundException(999));
        when(remoteClient.getMovements(eq(102L), anyString())).thenReturn(List.of());
    }
    @Test void fullReadPathWithRealJwtAndJdbc() throws Exception {
        mvc.perform(get("/api/atm/accounts/101/balance").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.availableBalance").value(1010));
    }
    @Test void missingAccountIs404() throws Exception {
        mvc.perform(get("/api/atm/accounts/999/balance").with(bearer("ATM"))).andExpect(status().isNotFound());
    }

    @Test void movementsAreOrderedAndLimited() throws Exception {
        mvc.perform(get("/api/atm/accounts/101/movements").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(3))
                .andExpect(jsonPath("$[0].amount").value(25))
                .andExpect(jsonPath("$[0].description").doesNotExist()).andExpect(jsonPath("$[0].date").doesNotExist());
    }
    @Test void missingAccountMovementsReturn404() throws Exception {
        mvc.perform(get("/api/atm/accounts/999/movements").with(bearer("ATM"))).andExpect(status().isNotFound());
    }
    @Test void existingAccountWithoutMovementsReturnsEmptyArray() throws Exception {
        mvc.perform(get("/api/atm/accounts/102/movements").with(bearer("ATM")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(0));
    }

    @Test void bothGetOperationsRelayBearer() throws Exception {
        String jwt = token("ATM");
        mvc.perform(get("/api/atm/accounts/101/balance")
                .header("Authorization", "Bearer " + jwt)).andExpect(status().isOk());
        mvc.perform(get("/api/atm/accounts/101/movements")
                .header("Authorization", "Bearer " + jwt)).andExpect(status().isOk());
        verify(remoteClient).getBalance(101, "Bearer " + jwt);
        verify(remoteClient).getMovements(101, "Bearer " + jwt);
    }

    @Test void downstreamFailureIs503WithoutFinancialData() throws Exception {
        when(remoteClient.getBalance(eq(101L), anyString()))
                .thenThrow(new com.duoc.banco_legacy.atm.client.AccountServiceUnavailableException(
                        new IllegalStateException("downstream")));
        mvc.perform(get("/api/atm/accounts/101/balance").with(bearer("ATM")))
                .andExpect(status().isServiceUnavailable())
                .andExpect(jsonPath("$.code").value("ACCOUNT_SERVICE_UNAVAILABLE"))
                .andExpect(jsonPath("$.availableBalance").doesNotExist());
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(strings={"{\"amount\":0}","{\"amount\":-1}","{\"amount\":null}","{}","{\"amount\":0.001}","{\"amount\":100000000000000000}"})
    void invalidWithdrawalIs400(String body) throws Exception {
        mvc.perform(post("/api/atm/accounts/101/withdrawals").with(bearer("ATM"))
                .contentType("application/json").content(body)).andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("WITHDRAWAL_REJECTED"));
    }
    @Test void withdrawalUpdatesBalanceAndRegistersVisibleMovement() throws Exception {
        mvc.perform(post("/api/atm/accounts/101/withdrawals").with(bearer("ATM"))
                        .contentType("application/json").content("{\"amount\":100}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("COMPLETED"))
                .andExpect(jsonPath("$.balanceBefore").value(1010))
                .andExpect(jsonPath("$.balanceAfter").value(910));

        assertThat(jdbc.queryForObject(
                "SELECT saldo_procesado FROM interes_procesado WHERE cuenta_id=101 ORDER BY id DESC LIMIT 1",
                BigDecimal.class)).isEqualByComparingTo("910");
        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM movimiento_anual_procesado WHERE cuenta_id=101 AND tipo_transaccion='retiro' AND monto=100",
                Integer.class)).isEqualTo(1);
        verifyNoInteractions(remoteClient);
    }

    @Test void movementInsertFailureRollsBackBalanceUpdate() {
        jdbc.execute("ALTER TABLE movimiento_anual_procesado ADD CONSTRAINT reject_atm_withdrawal CHECK (descripcion <> 'Retiro ATM')");
        try {
            assertThatThrownBy(() -> withdrawalService.withdraw(101, new BigDecimal("100")))
                    .isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
            assertThat(jdbc.queryForObject(
                    "SELECT saldo_procesado FROM interes_procesado WHERE cuenta_id=101 ORDER BY id DESC LIMIT 1",
                    BigDecimal.class)).isEqualByComparingTo("1010");
            assertThat(jdbc.queryForObject(
                    "SELECT COUNT(*) FROM movimiento_anual_procesado WHERE cuenta_id=101 AND tipo_transaccion='retiro'",
                    Integer.class)).isZero();
        } finally {
            jdbc.execute("ALTER TABLE movimiento_anual_procesado DROP CONSTRAINT IF EXISTS reject_atm_withdrawal");
        }
    }

    @Test void concurrentWithdrawalsCannotBothSpendSameBalance() throws Exception {
        jdbc.update("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (103,'Cuenta concurrente',150,0,150,'ahorro')");
        var start = new CountDownLatch(1);
        var executor = Executors.newFixedThreadPool(2);
        try {
            var tasks = List.of(
                    executor.submit(() -> withdrawConcurrently(start)),
                    executor.submit(() -> withdrawConcurrently(start)));
            start.countDown();
            var outcomes = List.of(tasks.get(0).get(10, TimeUnit.SECONDS), tasks.get(1).get(10, TimeUnit.SECONDS));

            assertThat(outcomes).containsExactlyInAnyOrder("COMPLETED", "REJECTED");
            assertThat(jdbc.queryForObject(
                    "SELECT saldo_procesado FROM interes_procesado WHERE cuenta_id=103 ORDER BY id DESC LIMIT 1",
                    BigDecimal.class)).isEqualByComparingTo("50");
            assertThat(jdbc.queryForObject(
                    "SELECT COUNT(*) FROM movimiento_anual_procesado WHERE cuenta_id=103 AND tipo_transaccion='retiro'",
                    Integer.class)).isEqualTo(1);
        } finally {
            executor.shutdownNow();
        }
    }
    @Test void missingWithdrawalAccountIs404() throws Exception {
        mvc.perform(post("/api/atm/accounts/999/withdrawals").with(bearer("ATM"))
                .contentType("application/json").content("{\"amount\":1}")).andExpect(status().isNotFound());
    }

    private String withdrawConcurrently(CountDownLatch start) throws Exception {
        start.await(5, TimeUnit.SECONDS);
        try {
            return withdrawalService.withdraw(103, new BigDecimal("100")).status();
        } catch (WithdrawalRejectedException expected) {
            return "REJECTED";
        }
    }

}
