package com.duoc.banco_legacy.web;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.mock.mockito.SpyBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import com.duoc.banco_legacy.core.repository.LegacyAccountReadRepository;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:web_integration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver","spring.datasource.username=sa","spring.datasource.password=",
        "spring.sql.init.mode=never"})
@AutoConfigureMockMvc
class WebDataIntegrationTests extends JwtTestSupport {
    @Autowired MockMvc mvc;
    @Autowired JdbcTemplate jdbc;
    @SpyBean LegacyAccountReadRepository repository;
    @BeforeEach void seedIsolatedH2() throws Exception {
        try(var connection = jdbc.getDataSource().getConnection()) {
            if (!connection.getMetaData().getURL().startsWith("jdbc:h2:mem:")) throw new IllegalStateException("Tests require isolated H2");
        }
        jdbc.execute("CREATE TABLE IF NOT EXISTS interes_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, nombre VARCHAR(120), saldo_original DECIMAL(19,2), tasa DECIMAL(8,4), saldo_procesado DECIMAL(19,2), tipo VARCHAR(20))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS movimiento_anual_procesado (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cuenta_id BIGINT, fecha DATE, tipo_transaccion VARCHAR(30), monto DECIMAL(19,2), descripcion VARCHAR(255))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS transaccion_procesada (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaccion_id BIGINT, fecha DATE, monto DECIMAL(19,2), tipo VARCHAR(20), anomalia BOOLEAN)");
        jdbc.update("DELETE FROM interes_procesado");
        jdbc.update("DELETE FROM movimiento_anual_procesado");
        jdbc.update("DELETE FROM transaccion_procesada");
        jdbc.update("INSERT INTO interes_procesado (cuenta_id,nombre,saldo_original,tasa,saldo_procesado,tipo) VALUES (101,'Ana',1000,0.01,1010,'ahorro'),(102,'Beto',100,0.01,101,'ahorro')");
        for(int i=1;i<=25;i++) jdbc.update("INSERT INTO movimiento_anual_procesado (cuenta_id,fecha,tipo_transaccion,monto,descripcion) VALUES (101,DATE '2026-01-01','deposito',?,'Detalle')",i);
        for(int i=1;i<=12;i++) jdbc.update("INSERT INTO transaccion_procesada (transaccion_id,fecha,monto,tipo,anomalia) VALUES (?,DATE '2026-01-01',2500,'debito',TRUE)",i);
    }
    @Test void fullReadPathWithRealJwtAndJdbc() throws Exception {
        mvc.perform(get("/api/web/accounts/101/dashboard").with(bearer("WEB")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.processedBalance").value(1010));
    }
    @Test void missingAccountIs404() throws Exception {
        mvc.perform(get("/api/web/accounts/999/dashboard").with(bearer("WEB"))).andExpect(status().isNotFound());
    }

    @Test void dashboardLimitsAndSingleBalanceRead() throws Exception {
        org.mockito.Mockito.clearInvocations(repository);
        mvc.perform(get("/api/web/accounts/101/dashboard").with(bearer("WEB")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.movements.length()").value(20))
                .andExpect(jsonPath("$.recentAnomalies.length()").value(10))
                .andExpect(jsonPath("$.movements[0].amount").value(25));
        org.mockito.Mockito.verify(repository, org.mockito.Mockito.times(1)).findLatestBalance(101);
    }

}
