server:
  port: 8087
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: bff-local
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 8087
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-eft-customer.sql
banking:
  account-service-name: banco-legacy-account-service
  http:
    connect-timeout: 2s
    read-timeout: 3s
resilience4j:
  circuitbreaker:
    instances:
      accountRegistry:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException